### ISSUE TITLE
Remove glslify from the initial template

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex#20]
It's not necessary also makes things complicated for Electron as it depends on node.js being installed on the users machine.

**Comment by teemWerk** [comment]
I don't know if this is the right place for this, or even the right place for the fix. On win32 at least I had trouble because the require uri that glslify-promise transform was pushing was missing some directory parentheses, you end up with it looking for folders that don't exist because it's mashed together a uri like ..\node_modulesglslify-promisewrapper.js

**Comment by vorg** [comment]
Not relevant with new glslfiy
